# Generated by Django 4.2.7 on 2025-09-24 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collectors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicezone",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="collectorperformance",
            name="collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="collectors.collector",
                verbose_name="采集器",
            ),
        ),
        migrations.AddField(
            model_name="collectordeployment",
            name="deployed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="部署者",
            ),
        ),
        migrations.AddField(
            model_name="collectordeployment",
            name="service_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="collectors.servicezone",
                verbose_name="服务区",
            ),
        ),
        migrations.AddField(
            model_name="collector",
            name="service_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="collectors.servicezone",
                verbose_name="服务区",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collector",
            unique_together={("host", "port")},
        ),
    ]
