# Generated by Django 4.2.7 on 2025-09-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("port", models.IntegerField(default=22, verbose_name="端口")),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("ssh", "SSH"),
                            ("snmp", "SNMP"),
                            ("api", "API"),
                            ("telnet", "Telnet"),
                            ("ftp", "FTP"),
                            ("sftp", "SFTP"),
                        ],
                        max_length=20,
                        verbose_name="协议类型",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="设备位置"),
                ),
                (
                    "vendor",
                    models.CharField(blank=True, max_length=100, verbose_name="厂商"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="型号"),
                ),
                (
                    "os_version",
                    models.CharField(blank=True, max_length=100, verbose_name="系统版本"),
                ),
                ("description", models.TextField(blank=True, verbose_name="设备描述")),
                (
                    "username",
                    models.CharField(blank=True, max_length=100, verbose_name="用户名"),
                ),
                ("password", models.TextField(blank=True, verbose_name="密码（加密）")),
                ("private_key", models.TextField(blank=True, verbose_name="私钥（加密）")),
                (
                    "protocol_params",
                    models.JSONField(default=dict, verbose_name="协议参数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("unknown", "未知"),
                            ("error", "错误"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="设备状态",
                    ),
                ),
                (
                    "last_check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后检查时间"),
                ),
                (
                    "response_time",
                    models.FloatField(blank=True, null=True, verbose_name="响应时间(ms)"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="分组名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分组描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备分组",
                "verbose_name_plural": "设备分组",
                "db_table": "device_groups",
            },
        ),
        migrations.CreateModel(
            name="DeviceStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("unknown", "未知"),
                            ("error", "错误"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(blank=True, null=True, verbose_name="响应时间(ms)"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "check_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="检查时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备状态历史",
                "verbose_name_plural": "设备状态历史",
                "db_table": "device_status_history",
                "ordering": ["-check_time"],
            },
        ),
    ]
