# Generated by Django 4.2.7 on 2025-09-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "device_filter",
                    models.JSONField(default=dict, verbose_name="设备过滤条件"),
                ),
                ("command", models.TextField(verbose_name="执行命令")),
                ("timeout", models.IntegerField(default=30, verbose_name="超时时间(秒)")),
                ("retry_count", models.IntegerField(default=3, verbose_name="重试次数")),
                (
                    "retry_interval",
                    models.IntegerField(default=5, verbose_name="重试间隔(秒)"),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("once", "单次执行"),
                            ("interval", "间隔执行"),
                            ("cron", "CRON表达式"),
                            ("manual", "手动执行"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="调度类型",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="CRON表达式"
                    ),
                ),
                (
                    "interval_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="执行间隔(秒)"),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次执行时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                            ("paused", "已暂停"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "total_executions",
                    models.IntegerField(default=0, verbose_name="总执行次数"),
                ),
                (
                    "success_executions",
                    models.IntegerField(default=0, verbose_name="成功执行次数"),
                ),
                (
                    "failed_executions",
                    models.IntegerField(default=0, verbose_name="失败执行次数"),
                ),
                (
                    "xxl_job_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="XXL-Job任务ID"
                    ),
                ),
                (
                    "xxl_job_group",
                    models.IntegerField(default=1, verbose_name="XXL-Job执行器组"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                ("variables", models.JSONField(default=dict, verbose_name="任务变量")),
                (
                    "notification_config",
                    models.JSONField(default=dict, verbose_name="通知配置"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "采集任务",
                "verbose_name_plural": "采集任务",
                "db_table": "collection_tasks",
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(max_length=100, unique=True, verbose_name="执行ID"),
                ),
                ("command", models.TextField(verbose_name="执行命令")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                            ("paused", "已暂停"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                ("result_data", models.TextField(blank=True, verbose_name="执行结果")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "exit_code",
                    models.IntegerField(blank=True, null=True, verbose_name="退出码"),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("max_retries", models.IntegerField(default=3, verbose_name="最大重试次数")),
                (
                    "xxl_job_log_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="XXL-Job日志ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "任务执行记录",
                "verbose_name_plural": "任务执行记录",
                "db_table": "task_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="模板名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("ssh", "SSH"),
                            ("snmp", "SNMP"),
                            ("api", "API"),
                            ("telnet", "Telnet"),
                            ("ftp", "FTP"),
                            ("sftp", "SFTP"),
                        ],
                        max_length=20,
                        verbose_name="协议类型",
                    ),
                ),
                ("command_template", models.TextField(verbose_name="命令模板")),
                ("timeout", models.IntegerField(default=30, verbose_name="超时时间(秒)")),
                ("retry_count", models.IntegerField(default=3, verbose_name="重试次数")),
                (
                    "retry_interval",
                    models.IntegerField(default=5, verbose_name="重试间隔(秒)"),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="CRON表达式"
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("once", "单次执行"),
                            ("interval", "间隔执行"),
                            ("cron", "CRON表达式"),
                            ("manual", "手动执行"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="调度类型",
                    ),
                ),
                (
                    "interval_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="执行间隔(秒)"),
                ),
                (
                    "result_parser",
                    models.CharField(blank=True, max_length=100, verbose_name="结果解析器"),
                ),
                (
                    "result_format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("xml", "XML"),
                            ("text", "纯文本"),
                            ("csv", "CSV"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="结果格式",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                ("variables", models.JSONField(default=dict, verbose_name="变量定义")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "任务模板",
                "verbose_name_plural": "任务模板",
                "db_table": "task_templates",
            },
        ),
    ]
