# Generated by Django 4.2.7 on 2025-09-24 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collectors", "0002_initial"),
        ("devices", "0002_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="collector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collectors.collector",
                verbose_name="执行采集器",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="devices.device",
                verbose_name="目标设备",
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.collectiontask",
                verbose_name="采集任务",
            ),
        ),
        migrations.AddField(
            model_name="collectiontask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="collectiontask",
            name="target_devices",
            field=models.ManyToManyField(
                blank=True, to="devices.device", verbose_name="目标设备"
            ),
        ),
        migrations.AddField(
            model_name="collectiontask",
            name="target_groups",
            field=models.ManyToManyField(
                blank=True, to="devices.devicegroup", verbose_name="目标设备组"
            ),
        ),
        migrations.AddField(
            model_name="collectiontask",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.tasktemplate",
                verbose_name="任务模板",
            ),
        ),
    ]
