# Generated by Django 4.2.7 on 2025-09-24 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("results", "0001_initial"),
        ("alerts", "0001_initial"),
        ("devices", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="devices",
            field=models.ManyToManyField(
                blank=True, to="devices.device", verbose_name="关联设备"
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, to="tasks.collectiontask", verbose_name="关联任务"
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="devices.device",
                verbose_name="关联设备",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="解决人",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="results.collectionresult",
                verbose_name="关联结果",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alerts.alertrule",
                verbose_name="告警规则",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.collectiontask",
                verbose_name="关联任务",
            ),
        ),
    ]
