# Generated by Django 4.2.7 on 2025-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverresource",
            name="description",
            field=models.TextField(blank=True, help_text="服务器描述信息", verbose_name="描述"),
        ),
    ]
